-- ============================================================
-- TUPÃ MOTORS - SNOWFLAKE SETUP (DBT + AIRFLOW READY)
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- ============================================================
-- ROLE (dbt)
-- ============================================================

CREATE ROLE IF NOT EXISTS DBT_DEV;

-- ============================================================
-- USER (dbt)
-- ============================================================

CREATE USER IF NOT EXISTS DEV
PASSWORD = 'dbtuser'
DEFAULT_ROLE = DBT_DEV
DEFAULT_WAREHOUSE = DEFAULT_WH
MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE DBT_DEV TO USER DEV;

-- ============================================================
-- WAREHOUSE
-- ============================================================

CREATE WAREHOUSE IF NOT EXISTS DEFAULT_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Grants Warehouse
GRANT USAGE ON WAREHOUSE DEFAULT_WH TO ROLE DBT_DEV;
GRANT OPERATE ON WAREHOUSE DEFAULT_WH TO ROLE DBT_DEV;

-- ============================================================
-- DATABASE
-- ============================================================

CREATE DATABASE IF NOT EXISTS TUPA_MOTORS;

GRANT USAGE ON DATABASE TUPA_MOTORS TO ROLE DBT_DEV;
GRANT CREATE SCHEMA ON DATABASE TUPA_MOTORS TO ROLE DBT_DEV;

USE DATABASE TUPA_MOTORS;

-- ============================================================
-- SCHEMAS
-- ============================================================

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;

-- Grants schemas
GRANT USAGE ON SCHEMA TUPA_MOTORS.BRONZE TO ROLE DBT_DEV;
GRANT USAGE ON SCHEMA TUPA_MOTORS.SILVER TO ROLE DBT_DEV;
GRANT USAGE ON SCHEMA TUPA_MOTORS.GOLD TO ROLE DBT_DEV;

GRANT CREATE TABLE ON SCHEMA TUPA_MOTORS.BRONZE TO ROLE DBT_DEV;
GRANT CREATE TABLE ON SCHEMA TUPA_MOTORS.SILVER TO ROLE DBT_DEV;
GRANT CREATE TABLE ON SCHEMA TUPA_MOTORS.GOLD TO ROLE DBT_DEV;

-- ============================================================
-- TABELAS - BRONZE
-- ============================================================

USE SCHEMA BRONZE;

CREATE TABLE IF NOT EXISTS ESTADOS (
    ID_ESTADOS NUMBER(38,0),
    ESTADO STRING,
    LOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM STRING
);

CREATE TABLE IF NOT EXISTS CIDADES (
    ID_CIDADES NUMBER(38,0),
    CIDADE STRING,
    ID_ESTADOS NUMBER(38,0),
    LOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM STRING
);

CREATE TABLE IF NOT EXISTS CONCESSIONARIAS (
    ID_CONCESSIONARIAS NUMBER(38,0),
    CONCESSIONARIA STRING,
    ENDERECO STRING,
    TELEFONE STRING,
    EMAIL STRING,
    ID_CIDADES NUMBER(38,0),
    LOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM STRING
);

CREATE TABLE IF NOT EXISTS VENDEDORES (
    ID_VENDEDORES NUMBER(38,0),
    NOME STRING,
    EMAIL STRING,
    TELEFONE STRING,
    DATA_ADMISSAO DATE,
    SALARIO NUMBER(12,2),
    META_MENSAL NUMBER(12,2),
    ATIVO BOOLEAN,
    ID_CONCESSIONARIAS NUMBER(38,0),
    LOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM STRING
);

CREATE TABLE IF NOT EXISTS CLIENTES (
    ID_CLIENTES NUMBER(38,0),
    CLIENTE STRING,
    CPF STRING,
    EMAIL STRING,
    TELEFONE STRING,
    CIDADE STRING,
    ESTADO STRING,
    RENDA_ESTIMADA NUMBER(12,2),
    DATA_NASCIMENTO DATE,
    DATA_CADASTRO TIMESTAMP_NTZ,
    LOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM STRING
);

CREATE TABLE IF NOT EXISTS VEICULOS (
    ID_VEICULOS NUMBER(38,0),
    ID_CONCESSIONARIAS NUMBER(38,0),
    FABRICANTE STRING,
    NOME STRING,
    TIPO STRING,
    ANO_MODELO NUMBER(4,0),
    COMBUSTIVEL STRING,
    CAMBIO STRING,
    COR STRING,
    PRECO_BASE NUMBER(12,2),
    ATIVO BOOLEAN,
    LOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM STRING
);

CREATE TABLE IF NOT EXISTS VENDAS (
    ID_VENDAS NUMBER(38,0),
    ID_CLIENTES NUMBER(38,0),
    ID_VENDEDORES NUMBER(38,0),
    ID_VEICULOS NUMBER(38,0),
    ID_CONCESSIONARIAS NUMBER(38,0),
    VALOR_PAGO NUMBER(12,2),
    DESCONTO NUMBER(12,2),
    FORMA_PAGAMENTO STRING,
    FINANCIAMENTO BOOLEAN,
    PARCELAS NUMBER(5,0),
    DATA_VENDA DATE,
    LOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM STRING
);

CREATE TABLE IF NOT EXISTS AVALIACOES_CLIENTES (
    ID_AVALIACAO NUMBER(38,0),
    ID_CLIENTES NUMBER(38,0),
    ID_CONCESSIONARIAS NUMBER(38,0),
    NOTA_ATENDIMENTO NUMBER(2,0),
    NOTA_VEICULO NUMBER(2,0),
    NOTA_PROCESSO_COMPRA NUMBER(2,0),
    COMENTARIO STRING,
    SENTIMENTO_IA STRING,
    DATA_AVALIACAO TIMESTAMP_NTZ,
    LOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM STRING
);

CREATE TABLE IF NOT EXISTS ETL_CONTROL (
    ID NUMBER AUTOINCREMENT,
    TABLE_NAME STRING,
    PIPELINE_NAME STRING,
    START_TIME TIMESTAMP_NTZ,
    END_TIME TIMESTAMP_NTZ,
    ROWS_EXTRACTED NUMBER,
    ROWS_LOADED NUMBER,
    STATUS STRING,
    MESSAGE STRING,
    EXECUTION_TIME_SECONDS NUMBER(10,2)
);

-- ============================================================
-- FINAL PERMISSIONS CHECK
-- ============================================================

SHOW GRANTS TO ROLE DBT_DEV;
SHOW GRANTS ON DATABASE TUPA_MOTORS;
SHOW TABLES IN SCHEMA TUPA_MOTORS.BRONZE;